# Generated by Django 6.0 on 2026-03-13 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_material_auto_reorder_material_custom_reorder_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('bom_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Base quantity produced by this recipe', max_digits=10)),
                ('product', models.ForeignKey(help_text='The finished product being created', on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='BomComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity required to make the base BOM quantity', max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mrp.billofmaterial')),
                ('component', models.ForeignKey(help_text='The raw material needed', on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('mo_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('qty_to_produce', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed / In Progress'), ('done', 'Done')], default='draft', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrp.billofmaterial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
    ]
