# Generated by Django 6.0 on 2026-03-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicalmaterial_company_and_more'),
        ('mrp', '0002_historicalbillofmaterial_historicalbomcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbillofmaterial',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicalbomcomponent',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicalmanufacturingorder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
    ]
