# Generated by Django 6.0 on 2026-03-12 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_abc_class_material_churn_rate_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('out_invoice', 'Customer Invoice (Sales)'), ('in_invoice', 'Vendor Bill (Purchases)')], max_length=20)),
                ('source_document', models.CharField(blank=True, help_text='e.g., SO-1234', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
            ],
        ),
    ]
