# Generated by Django 6.0 on 2026-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
