# Generated by Django 6.0 on 2026-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='material',
            name='churn_rate',
            field=models.FloatField(default=0, help_text='Percentage of stock turnover'),
        ),
        migrations.AddField(
            model_name='material',
            name='forecast_30d',
            field=models.FloatField(default=0, help_text='Predicted sales for next 30 days'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_perf',
            field=models.FloatField(default=0, help_text='Supplier On-Time Percentage'),
        ),
    ]
