# Generated by Django 6.0 on 2026-03-12 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_abc_class_material_churn_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='auto_reorder',
            field=models.BooleanField(default=False, help_text='Enable automated Draft PO creation'),
        ),
        migrations.AddField(
            model_name='material',
            name='custom_reorder_qty',
            field=models.IntegerField(blank=True, help_text='If set, orders this exact amount. Otherwise fills to Max.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partner'),
        ),
    ]
