# Generated by Django 6.0 on 2026-03-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_auto_reorder_material_custom_reorder_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sales Orders', max_length=100)),
                ('code', models.CharField(help_text='e.g., sales.order', max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, help_text='e.g., SO-', max_length=20)),
                ('padding', models.IntegerField(default=4, help_text='Number of digits (e.g., 4 -> 0001)')),
                ('next_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique Stock Keeping Unit', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
