# Generated by Django 6.0 on 2026-03-14 15:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsequence_alter_material_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('sku', models.CharField(blank=True, db_index=True, help_text='Unique Stock Keeping Unit', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('min_stock_level', models.IntegerField(default=10, help_text='Reorder Point')),
                ('max_stock_level', models.IntegerField(default=100, help_text='Target Maximum')),
                ('lead_time_days', models.IntegerField(default=1, help_text='Days to receive from supplier')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('auto_reorder', models.BooleanField(default=False, help_text='Enable automated Draft PO creation')),
                ('custom_reorder_qty', models.IntegerField(blank=True, help_text='If set, orders this exact amount. Otherwise fills to Max.', null=True)),
                ('abc_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1)),
                ('forecast_30d', models.FloatField(default=0, help_text='Predicted sales for next 30 days')),
                ('churn_rate', models.FloatField(default=0, help_text='Percentage of stock turnover')),
                ('supplier_perf', models.FloatField(default=0, help_text='Supplier On-Time Percentage')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.productcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preferred_supplier', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.partner')),
                ('uom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.uom')),
            ],
            options={
                'verbose_name': 'historical material',
                'verbose_name_plural': 'historical materials',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartner',
            fields=[
                ('partner_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pricelist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.pricelist')),
            ],
            options={
                'verbose_name': 'historical partner',
                'verbose_name_plural': 'historical partners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
