# Generated by Django 6.0 on 2026-03-15 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalmaterial_historicalpartner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='auto_reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='churn_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='custom_reorder_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='forecast_30d',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='lead_time_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='max_stock_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='supplier_perf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='auto_reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='churn_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='custom_reorder_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='forecast_30d',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='lead_time_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='material',
            name='max_stock_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier_perf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='systemsequence',
            name='code',
            field=models.CharField(help_text='e.g., sales.order', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='material',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='systemsequence',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='uom',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='systemsequence',
            unique_together={('company', 'code')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
