# Generated by Django 6.0 on 2026-03-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_alter_historicalmaterial_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django native permissions linked to this role.', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.workspacerole'),
        ),
    ]
