# Generated by Django 6.0 on 2026-01-14 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('received', 'Done')], default='draft', max_length=20)),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('so_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_mode', models.CharField(choices=[('normal', 'Normal'), ('green', 'Green Mode')], max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partial', 'Partial'), ('shipped', 'Done'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.salesorder')),
            ],
        ),
    ]
