# Generated by Django 6.0 on 2026-03-14 15:05

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsequence_alter_material_sku_and_more'),
        ('logistics', '0002_alter_purchaseorder_po_id_alter_salesorder_so_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('po_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('received', 'Done')], default='draft', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.partner')),
            ],
            options={
                'verbose_name': 'historical purchase order',
                'verbose_name_plural': 'historical purchase orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('so_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_mode', models.CharField(choices=[('normal', 'Normal'), ('green', 'Green Mode')], max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partial', 'Partial'), ('shipped', 'Done'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.partner')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sales order',
                'verbose_name_plural': 'historical sales orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
