# Generated by Django 6.0 on 2026-03-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicalmaterial_company_and_more'),
        ('logistics', '0003_historicalpurchaseorder_historicalsalesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicalsalesorder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
    ]
