# Generated by Django 6.0 on 2026-01-14 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('ref', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('done', 'Applied')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPickingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('lot_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='StockPicking',
            fields=[
                ('picking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Ready'), ('done', 'Done')], default='draft', max_length=20)),
                ('picking_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockpickingtype')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('internal', 'Internal Warehouse'), ('customer', 'Customer Location'), ('supplier', 'Vendor Location'), ('loss', 'Inventory Loss')], default='internal', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='default_dest_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_type_dest', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='stockpickingtype',
            name='default_source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_type_src', to='inventory.storagelocation'),
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='draft', max_length=20)),
                ('reference', models.CharField(help_text='Source Doc (PO/SO)', max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('picking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='inventory.stockpicking')),
                ('location_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_in', to='inventory.storagelocation')),
                ('location_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_out', to='inventory.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storagelocation'),
        ),
        migrations.CreateModel(
            name='StockQuant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_incoming', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklot')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storagelocation')),
            ],
            options={
                'unique_together': {('material', 'location', 'lot')},
            },
        ),
    ]
