# Generated by Django 6.0 on 2026-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmove_move_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
