# Generated by Django 6.0 on 2026-03-13 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_material_auto_reorder_material_custom_reorder_qty_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('opp_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g., Summer Restock Order', max_length=200)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('probability', models.IntegerField(default=10, help_text='Probability of winning (%)')),
                ('state', models.CharField(choices=[('new', 'New Lead'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, to='core.partner')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='logistics.salesorder')),
            ],
        ),
    ]
