# Generated by Django 6.0 on 2026-03-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_material_auto_reorder_material_custom_reorder_qty_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.opportunity')),
            ],
        ),
    ]
